<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <title>Suma administrative tools</title>
</head>
<body>
    <?php echo $this->render('admin/header.phtml'); ?>
    <h3><a href="<?php echo $this->baseUrl(); ?>/admin/locations">Edit locations</a></h3>
    <h3><a href="<?php echo $this->baseUrl(); ?>/admin/initiatives">Edit initiatives</a></h3>
    <h3><a href="<?php echo $this->baseUrl(); ?>/admin/sessions">Sessions List</a></h3>
    <h3><a href="<?php echo $this->baseUrl(); ?>/admin/jsonimport">Direct JSON Import</a></h3>
    <?php echo $this->render('admin/footer.phtml'); ?>
</body>
</html>
