<!DOCTYPE html>
<?php $baseDir = Zend_Controller_Front::getInstance()->getBaseUrl(); ?>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="<?php echo $baseDir; ?>/css/jquery-ui-theme/css/cupertino/jquery-ui-1.8.14.custom.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo $baseDir; ?>/css/admin.css" />

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.21/jquery-ui.js" type="text/javascript"></script>
        <script src="<?php echo $baseDir; ?>/js/nestedSortable/nestedSortable.js" type="text/javascript"></script>
        <script src="<?php echo $baseDir; ?>/js/jquery.history.html4html5/jquery.history.js" type="text/javascript"></script>
        <script type="text/javascript">
        <?php
            if (isset($_GET['initID'])) {
                echo 'var recoveredID = ' . $_GET['initID'] . ';';
            } else {
                echo 'var recoveredID = null;';
            }

            echo "\nvar basePath='$baseDir';\n";
        ?>
        </script>
        <script src="<?php echo $baseDir; ?>/js/views/admin/initiatives.js" type="text/javascript"></script>
    </head>
    <body>
        <?php echo $this->render('admin/header.phtml'); ?>
        <div id="newInitDialog" style="display:none">
            <form>
                <input type="text" id="newInitTitleInput" name="newInitTitleInput" value="" /><br>
                <textarea id="newInitDescInput" name="newInitDescInput"></textarea><br><br>
                <div><b>Note: Setting location tree is permanent. If you haven't created your location tree yet, please do that first.</b></div>
                <br>
                <select id="locRootSel">
                    <option value="" SELECTED>Select a location tree</option>
                <?php
                foreach($this->roots as $root)
                {
                    echo '<option value="'.$root->getMetadata('id').'">'.$root->getMetadata('title').'</option>';
                }
                ?>
                </select>
            </form>
        </div>

        <div id="initEditDialog" style="display:none">
            <form class="deadForm">
                <input type="text" id="initTitleInput" name="initTitleInput" value="" /><br>
                <textarea id="initDescInput" name="initDescInput"></textarea><br><br>
                <br>
            </form>
        </div>
        <div id="actEditDialog" style="display:none">
            <form class="deadForm">
                <input type="text" id="actTitleInput" name="actTitleInput" value="" /><br>
                <textarea id="actDescInput" name="actDescInput"></textarea><br>
                <span id="enableInput"><br>Enabled? <input name="actEnabledCheck" type="checkbox" id="actEnabledCheck" /><br></span>
                <div id="activityGroupFormContent">
                    <span id="requiredGroupInput"><br>Required for data collection? <input name="actGroupRequiredCheck" type="checkbox" id="actGroupRequiredCheck" /><br></span>
                    <span id="allowMultiGroupInput"><br>Allow multiple activities? <input name="actGroupMultiCheck" type="checkbox" id="actGroupMultiCheck" /><br></span>
                </div>
            </form>
            <p>Activity edits will not be permanent until the entire activity list is saved.</p>
        </div>

        <div>
        <form id="initForm">
        <select id="initSelect">
        <?php
        foreach($this->initiatives as $init)
        {
            echo '<option value="'.$init->getMetadata('id').'">'.$init->getMetadata('title').'</option>';
        }
        ?>
        </select>
        <input id="initSelBtn" type="submit" value="Display Initiative" />
        </div>
        </form>
        <h3><a href="#" id="createInitLink">Create new initiative</a></h3>
        <div id="metadata"></div>
        <?php echo $this->render('admin/footer.phtml'); ?>
    </body>
</html>
