<!DOCTYPE html>
<?php $baseDir = Zend_Controller_Front::getInstance()->getBaseUrl(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
    <head>
        <title>Suma Location Tree Editor</title>
        <link rel="stylesheet" type="text/css" href="<?php echo $baseDir; ?>/css/jquery-ui-theme/css/cupertino/jquery-ui-1.10.3.custom.min.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo $baseDir; ?>/css/admin.css" />

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js" type="text/javascript"></script>
        <script src="<?php echo $baseDir; ?>/js/nestedSortable/nestedSortable.js" type="text/javascript"></script>
        <script src="<?php echo $baseDir; ?>/js/jquery.history.html4html5/jquery.history.js" type="text/javascript"></script>
        <script src="<?php echo $baseDir; ?>/js/lo-dash/lodash.compat.min.js" type="text/javascript"></script>

        <script type="text/javascript">
        <?php
            if (isset($_GET['locID'])) {
                echo 'var recoveredID = ' . $_GET['locID'] . ';';
            } else {
                echo 'var recoveredID = null';
            }

            echo "\nvar basePath='$baseDir';\n";

        ?>
        </script>

        <script src="<?php echo $baseDir; ?>/js/views/admin/locations.js" type="text/javascript"></script>

        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
        <title></title>
    </head>
    <body>
    <?php echo $this->render('admin/header.phtml'); ?>
        <div id="editingForms">
            <div id="newTreeDialog" style="display:none">
                <form>
                    <input type="text" id="newTreeTitleInput" name="newTreeTitleInput" value="" /><br />
                    <textarea id="newTreeDescInput" name="newTreeDescInput"></textarea><br /><br />
                </form>
            </div>
            <div id="treeEditDialog" style="display:none">
                <form class="deadForm">
                    <input type="text" id="treeTitleInput" name="treeTitleInput" value="" /><br />
                    <textarea id="treeDescInput" name="treeDescInput"></textarea><br /><br />
                    <br />
                </form>
                <p>Location tree edits will not be permanent until the entire location tree is saved.</p>
            </div>
            <div id="locEditDialog" style="display:none">
                <form class="deadForm">
                    <input type="text" id="locTitleInput" name="locTitleInput" value="" /><br />
                    <textarea id="locDescInput" name="locDescInput"></textarea><br /><br />
                    Enabled? <input name="locEnabledCheck" type="checkbox" id="locEnabledCheck" />
                    <br />
                </form>
                <p>Location edits will not be permanent until the entire location tree is saved.</p>
            </div>
        </div>
        <form id="locForm">
        <select id="rootSelect">

        <?php
        foreach ($this->roots as $root) {
            echo '<option value="'.$root->getMetadata('id').'">'.$root->getMetadata('title').'</option>';
        }
        ?>
        </select>
        <input id="locSelBtn" type="submit" value="Display Locations" />
        <div id="locArea">
        </div>
        </form>
        <h3><a href="#" id="createTreeLink">Create new location tree</a></h3>
        <?php echo $this->render('admin/footer.phtml'); ?>
    </body>
</html>
