<h3>Location tree title: <span id="treeTitle"><?php echo $this->location->getMetadata('title'); ?></span></h3>
<h3>Location tree description: <span id="treeDesc"><?php echo $this->location->getMetadata('description'); ?></span></h3>
<div id="treeID"><?php echo $this->location->getMetadata('id'); ?></div>
<a id="editTree" href="#">Edit tree title and description</a>
<br />
<br />
<div><a id="addLoc" href="#">Add a location</a></div>
<ol id="locations" class="sortable">
<?php
$this->listChildLocs($this->location, TRUE);
?>
</ol>
<br />
<h3><a id="saveLocs" href="#">Save Locations</a></h3>
