<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <title>Suma administrative tools</title>
</head>
<body>
<?php
$this->render('admin/header.phtml');

$session = $this->session;
$init = $this->init;
$trans = $session->getTransById($session->getMetadata('fk_transaction'));
$counts = $session->getCounts();
$countTotal = $session->getCountTotal();
$activities = $init->getActivities();


$sum = (is_null($countTotal)) ? 'Null' : $countTotal;

echo '<p><strong>InitTitle:</strong> ' . $init->getMetadata('title');
echo ' <strong>Session ID:</strong>'.$session->getMetadata('id').', <strong>Start:</strong>'.$session->getMetadata('start')
     .', <strong>End:</strong>'.$session->getMetadata('end').', <strong>TranS:</strong>'.$trans['start']
     .', <strong>TranE:</strong>'.$trans['end'].', <strong>Total: </strong>'.$sum.'</p>';

     
$locations = $this->locations;
echo '<table border="1"><tr>';
$locHash = array();
foreach($locations as $location)
{
    echo '<th>'. $location->getMetadata('title') . '</th>';
    $locHash[$location->getMetadata('id')] = $location->getMetadata('title');
}
echo '</tr><tr style="text-align:center;">';     

foreach($locHash as $key => $val)
{
    $locCountTotal = $session->getCountTotalByLoc($key);
    $sum = (is_null($locCountTotal)) ? 'Null' : $locCountTotal;
    echo '<td>'.$sum.'</td>';
}
echo '</tr></table>';

$actHash = array();
foreach($activities as $activity)
{
    $actHash[$activity->getMetadata('id')] = $activity->getMetadata('title');
}

foreach($counts as $count)
{
    $activitiesJoin = $session->getJoinByCntId($count['id']);
    
    echo '<p>';
    echo '<strong>Count ID:</strong> '.$count['id'].'<br>';
    echo '<strong>Count Time:</strong> '.$count['occurrence'].'<br>';
    echo '<strong>Count Number:</strong> '.$count['number'].'<br>';
    echo '<strong>Count Location ID:</strong> '.$count['fk_location'].'<br>';
    echo '<strong>Location Title:</strong> '.$locHash[$count['fk_location']].'<br>';
    
    foreach ($activitiesJoin as $join)
    {
        echo '<strong>Activity ID:</strong> '.$join['fk_activity'].'<br>';
        echo '<strong>Activity Title:</strong> '.$actHash[$join['fk_activity']].'<br>';
    }
    echo '</p>';
}

$this->render('admin/footer.phtml');
?>
</body>
</html>